### ISSUE TITLE
Known vulnerabilities not as expected

### ISSUE THREAD

**Issue by digimangos** [ActionsDesk/github-actions-details-action#51]
### Describe the bug

Perhaps it's a misunderstanding, but I'm unclear what the field "Known vulnerabilities" represents, as I deliberately made an action which included packages (although not used by the code), containing critical vulnerabilities, yet the action reports none.

![image](https://user-images.githubusercontent.com/49808393/184919062-b4dcd4ed-e40b-48f3-82de-1895c381f236.png)

However from dependabot, there are two issues:

![image](https://user-images.githubusercontent.com/49808393/184919287-d8b43ea4-005b-4bd0-aa7e-f34aab337562.png)

### To Reproduce

1. Configure this action. 
2. Add "digimangos-playground/delibrately-vulnerable-action@main" to the allow list and commit to a new branch. 
3. Create a PR from the branch to "main" and await the result from the action.

### Expected behavior

I expected the action to show 2 vulnerabilities.

**Comment by stoe** [comment]
@digimangos not seeing the "Dependabot alerts" tab when navigating to https://github.com/digimangos-playground/delibrately-vulnerable-action/security

![image](https://user-images.githubusercontent.com/203805/185104717-e45b1232-bc1c-4747-8731-c8fa0e284ba5.png)

Might be a permission thingy.

**Comment by digimangos** [comment]
The README.md files says to create a PAT with no scopes (presumably because it's scanning public repos), let me give it some scope and see if it picks up the dependabot alerts which are hidden as you mentioned.

**Comment by stoe** [comment]
> give it some scope and see if it picks up the dependabot alerts which are hidden as you mentioned.

It won't. That info seems to be no longer visible through the APIs.

**Comment by digimangos** [comment]
So... @stoe what scenario would give a positive value in the "known vulnerabilities" section?
